#checkpoint: /home/alex/workspace/ml-data/cae/model_yt_small_final.state
checkpoint: /content/drive/MyDrive/model_yt_small_final.state
exp_name: testing
batch_every: 100
shuffle: false
#dataset_path: /home/alex/workspace/ml-data/cae/datasets/testing
#dataset_path: /content/drive/MyDrive/testing
dataset_path: /content/drive/MyDrive/ResizeTest
num_workers: 1
device: cuda
